Module6 task5
MattStefanski/Kodilla pull request #1
Opened 2018-04-16 20:56 UTC by MattStefanski

2018-04-17 09:40 UTC, MARudnicki requested changes

2018-04-17 09:40 UTC, MARudnicki commented on kodilla-testing/src/test/java/com/kodilla/testing/forum/statistics/ForumStatisticsTestsSuit.java
> +    }
podziel to prosze na kilka roznych testow. Dokladnie 7 zgodnie z trescia zadania
```
gdy liczba postów = 0,
gdy liczba postów = 1000,
gdy liczba komentarzy = 0,
gdy liczba komentarzy < liczba postów,
gdy liczba komentarzy > liczba postów,
gdy liczba użytkowników = 0,
gdy liczba użytkowników = 100.

2018-04-17 18:57 UTC, MattStefanski commented
Poprawione

2018-04-18 06:07 UTC, MARudnicki requested changes

2018-04-18 06:07 UTC, MARudnicki commented on kodilla-testing/src/test/java/com/kodilla/testing/forum/statistics/ForumStatisticsTestsSuit.java
> +        List<String> usLs1 = Lists.newArrayList();
we wszystkich testach jest nieuzywana zmienna usLs1. Do usuniecia

2018-04-18 06:07 UTC, MARudnicki commented on kodilla-testing/build.gradle
> +    testCompile "org.mockito:mockito-core:2.+"
nie uzywaj `+` to powoduje ryzyko ze przy ktoryms buildzie wersja sie zmieni i cos przestanie dzialac

2018-04-18 06:07 UTC, MARudnicki commented on kodilla-testing/build.gradle
> +    testCompile "org.mockito:mockito-core:2.+"
zastap mockito przez
testCompile group: 'org.mockito', name: 'mockito-all', version: '1.8.4'

2018-04-18 06:07 UTC, MARudnicki commented on kodilla-testing/src/main/java/com/kodilla/testing/forum/statistics/StatisticsCalculator.java
> +        if(statistics.postsCount()>0) {
co jesli userNames == 0 ? Algorytm tez powinein sie wykonac. Mozesz uzyc np Double.INFINITY.

2018-04-18 19:40 UTC, MARudnicki commented on kodilla-testing/build.gradle
> +    testCompile "org.mockito:mockito-core:2.+"
testCompile group: 'org.mockito', name: 'mockito-core', version: '2.18.0'

2018-04-18 21:34 UTC, MattStefanski commented
Poprawione

2018-04-19 18:14 UTC, MattStefanski commented
Hej, tutaj podobnie w pliku w tym branchu mam:   testCompile group: 'org.mockito', name: 'mockito-core', version: '2.13.0'

2018-04-21 11:42 UTC, merged