Module6 ,tasks 1,2,3
MattStefanski/Kodilla pull request #3
Opened 2018-04-16 20:59 UTC by MattStefanski

2018-04-18 05:49 UTC, MARudnicki requested changes

2018-04-18 05:49 UTC, MARudnicki commented on kodilla-testing/src/main/java/com/kodilla/testing/collection/OddNumbersExterminator.java
> +            while (arr.remove(arr2.get(i))) {
Nie powinienes zmieniac obiektu imputu. Exterminate powinno przyjmowac liste1, Nie zmieniac jej, zbudowac i zwrocic druga liste

2018-04-18 05:49 UTC, MARudnicki commented on kodilla-testing/src/main/java/com/kodilla/testing/collection/OddNumbersExterminator.java
> +            while (arr.remove(arr2.get(i))) {
To rozwiazanie jest bardzo zagmatwane. Rzuc okiem na to
```
public List<Integer> exterminate(List<Integer> number) {

        List<Integer> result = Lists.newArrayList();

        for (Integer integer : number) {
            if (integer % 2 == 0) {
                result.add(integer);
            }
        }
        return result;
    }
```

2018-04-18 05:49 UTC, MARudnicki commented on kodilla-testing/src/test/java/com/kodilla/testing/collection/CollectionTestSuite.java
> +            }
ten test jest zbyt zawily. Wystarczylo by
```
        //Given
        ArrayList<Integer> givenArray = Lists.newArrayList(2, 3, 4, 1, 2);
        
        //When
        ArrayList<Integer> testingArray = new OddNumbersExterminator().exterminate(Lists.newArrayList(2, 3, 4, 1, 2));

        //Then
        for(Integer integer : testingArray){
            Assert.assertTrue(integer % 2 == 0);
        }

2018-04-18 05:50 UTC, MARudnicki commented
Dodatkowo dla pustej listy, exterminator powinien zwracac pusta liste, nie null'a

2018-04-18 21:34 UTC, MattStefanski commented
Poprawione

2018-04-19 05:43 UTC, MARudnicki commented
dalej testy nie sa poprawione - CollectionTestSuit
dalej exterminator nie jest poprawiony - OddNumbersExterminator

2018-04-19 18:06 UTC, MattStefanski commented
Hej, dziwne ja w plikach widzę, że ArrayList zwraca pustą listę, a OddNumbersExterminator został uproszczony, czy o coś innego jeszcze chodzi?

2018-04-21 11:44 UTC, merged